/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimPenyusunRouteImport } from './routes/tim-penyusun'
import { Route as TimEvaluasiRouteImport } from './routes/tim-evaluasi'
import { Route as KepalaOpdRouteImport } from './routes/kepala-opd'
import { Route as KepalaBiroOrganisasiRouteImport } from './routes/kepala-biro-organisasi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimPenyusunIndexRouteImport } from './routes/tim-penyusun.index'
import { Route as TimEvaluasiIndexRouteImport } from './routes/tim-evaluasi.index'
import { Route as KepalaOpdIndexRouteImport } from './routes/kepala-opd.index'
import { Route as KepalaBiroOrganisasiIndexRouteImport } from './routes/kepala-biro-organisasi.index'
import { Route as TimPenyusunSopSayaRouteImport } from './routes/tim-penyusun.sop-saya'
import { Route as TimEvaluasiTtdElektronikRouteImport } from './routes/tim-evaluasi.ttd-elektronik'
import { Route as TimEvaluasiPenugasanRouteImport } from './routes/tim-evaluasi.penugasan'
import { Route as KepalaOpdTtdElektronikRouteImport } from './routes/kepala-opd.ttd-elektronik'
import { Route as KepalaOpdPelaksanaSopRouteImport } from './routes/kepala-opd.pelaksana-sop'
import { Route as KepalaOpdManajemenTimPenyusunRouteImport } from './routes/kepala-opd.manajemen-tim-penyusun'
import { Route as KepalaOpdManajemenPeraturanRouteImport } from './routes/kepala-opd.manajemen-peraturan'
import { Route as KepalaOpdInitiateProyekRouteImport } from './routes/kepala-opd.initiate-proyek'
import { Route as KepalaOpdDaftarSopRouteImport } from './routes/kepala-opd.daftar-sop'
import { Route as KepalaBiroOrganisasiTtdElektronikRouteImport } from './routes/kepala-biro-organisasi.ttd-elektronik'
import { Route as KepalaBiroOrganisasiManajemenTimEvaluasiRouteImport } from './routes/kepala-biro-organisasi.manajemen-tim-evaluasi'
import { Route as KepalaBiroOrganisasiManajemenOpdRouteImport } from './routes/kepala-biro-organisasi.manajemen-opd'
import { Route as KepalaBiroOrganisasiManajemenEvaluasiSopRouteImport } from './routes/kepala-biro-organisasi.manajemen-evaluasi-sop'
import { Route as TimEvaluasiPenugasanIndexRouteImport } from './routes/tim-evaluasi.penugasan.index'
import { Route as KepalaBiroOrganisasiManajemenEvaluasiSopIndexRouteImport } from './routes/kepala-biro-organisasi.manajemen-evaluasi-sop.index'
import { Route as ValidasiTtdBerhasilRouteImport } from './routes/validasi.ttd.berhasil'
import { Route as ValidasiPengesahanIdRouteImport } from './routes/validasi.pengesahan.$id'
import { Route as TimPenyusunDetailSopIdRouteImport } from './routes/tim-penyusun.detail-sop.$id'
import { Route as TimEvaluasiPelaksanaanIdRouteImport } from './routes/tim-evaluasi.pelaksanaan.$id'
import { Route as KepalaOpdDetailSopIdRouteImport } from './routes/kepala-opd.detail-sop.$id'
import { Route as KepalaBiroOrganisasiManajemenEvaluasiSopBuatRouteImport } from './routes/kepala-biro-organisasi.manajemen-evaluasi-sop.buat'
import { Route as TimEvaluasiPenugasanDetailIdRouteImport } from './routes/tim-evaluasi.penugasan.detail.$id'
import { Route as KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRouteImport } from './routes/kepala-biro-organisasi.manajemen-evaluasi-sop.detail.$id'

const TimPenyusunRoute = TimPenyusunRouteImport.update({
  id: '/tim-penyusun',
  path: '/tim-penyusun',
  getParentRoute: () => rootRouteImport,
} as any)
const TimEvaluasiRoute = TimEvaluasiRouteImport.update({
  id: '/tim-evaluasi',
  path: '/tim-evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KepalaOpdRoute = KepalaOpdRouteImport.update({
  id: '/kepala-opd',
  path: '/kepala-opd',
  getParentRoute: () => rootRouteImport,
} as any)
const KepalaBiroOrganisasiRoute = KepalaBiroOrganisasiRouteImport.update({
  id: '/kepala-biro-organisasi',
  path: '/kepala-biro-organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimPenyusunIndexRoute = TimPenyusunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimPenyusunRoute,
} as any)
const TimEvaluasiIndexRoute = TimEvaluasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimEvaluasiRoute,
} as any)
const KepalaOpdIndexRoute = KepalaOpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaBiroOrganisasiIndexRoute =
  KepalaBiroOrganisasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => KepalaBiroOrganisasiRoute,
  } as any)
const TimPenyusunSopSayaRoute = TimPenyusunSopSayaRouteImport.update({
  id: '/sop-saya',
  path: '/sop-saya',
  getParentRoute: () => TimPenyusunRoute,
} as any)
const TimEvaluasiTtdElektronikRoute =
  TimEvaluasiTtdElektronikRouteImport.update({
    id: '/ttd-elektronik',
    path: '/ttd-elektronik',
    getParentRoute: () => TimEvaluasiRoute,
  } as any)
const TimEvaluasiPenugasanRoute = TimEvaluasiPenugasanRouteImport.update({
  id: '/penugasan',
  path: '/penugasan',
  getParentRoute: () => TimEvaluasiRoute,
} as any)
const KepalaOpdTtdElektronikRoute = KepalaOpdTtdElektronikRouteImport.update({
  id: '/ttd-elektronik',
  path: '/ttd-elektronik',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaOpdPelaksanaSopRoute = KepalaOpdPelaksanaSopRouteImport.update({
  id: '/pelaksana-sop',
  path: '/pelaksana-sop',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaOpdManajemenTimPenyusunRoute =
  KepalaOpdManajemenTimPenyusunRouteImport.update({
    id: '/manajemen-tim-penyusun',
    path: '/manajemen-tim-penyusun',
    getParentRoute: () => KepalaOpdRoute,
  } as any)
const KepalaOpdManajemenPeraturanRoute =
  KepalaOpdManajemenPeraturanRouteImport.update({
    id: '/manajemen-peraturan',
    path: '/manajemen-peraturan',
    getParentRoute: () => KepalaOpdRoute,
  } as any)
const KepalaOpdInitiateProyekRoute = KepalaOpdInitiateProyekRouteImport.update({
  id: '/initiate-proyek',
  path: '/initiate-proyek',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaOpdDaftarSopRoute = KepalaOpdDaftarSopRouteImport.update({
  id: '/daftar-sop',
  path: '/daftar-sop',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaBiroOrganisasiTtdElektronikRoute =
  KepalaBiroOrganisasiTtdElektronikRouteImport.update({
    id: '/ttd-elektronik',
    path: '/ttd-elektronik',
    getParentRoute: () => KepalaBiroOrganisasiRoute,
  } as any)
const KepalaBiroOrganisasiManajemenTimEvaluasiRoute =
  KepalaBiroOrganisasiManajemenTimEvaluasiRouteImport.update({
    id: '/manajemen-tim-evaluasi',
    path: '/manajemen-tim-evaluasi',
    getParentRoute: () => KepalaBiroOrganisasiRoute,
  } as any)
const KepalaBiroOrganisasiManajemenOpdRoute =
  KepalaBiroOrganisasiManajemenOpdRouteImport.update({
    id: '/manajemen-opd',
    path: '/manajemen-opd',
    getParentRoute: () => KepalaBiroOrganisasiRoute,
  } as any)
const KepalaBiroOrganisasiManajemenEvaluasiSopRoute =
  KepalaBiroOrganisasiManajemenEvaluasiSopRouteImport.update({
    id: '/manajemen-evaluasi-sop',
    path: '/manajemen-evaluasi-sop',
    getParentRoute: () => KepalaBiroOrganisasiRoute,
  } as any)
const TimEvaluasiPenugasanIndexRoute =
  TimEvaluasiPenugasanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TimEvaluasiPenugasanRoute,
  } as any)
const KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute =
  KepalaBiroOrganisasiManajemenEvaluasiSopIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => KepalaBiroOrganisasiManajemenEvaluasiSopRoute,
  } as any)
const ValidasiTtdBerhasilRoute = ValidasiTtdBerhasilRouteImport.update({
  id: '/validasi/ttd/berhasil',
  path: '/validasi/ttd/berhasil',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidasiPengesahanIdRoute = ValidasiPengesahanIdRouteImport.update({
  id: '/validasi/pengesahan/$id',
  path: '/validasi/pengesahan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TimPenyusunDetailSopIdRoute = TimPenyusunDetailSopIdRouteImport.update({
  id: '/detail-sop/$id',
  path: '/detail-sop/$id',
  getParentRoute: () => TimPenyusunRoute,
} as any)
const TimEvaluasiPelaksanaanIdRoute =
  TimEvaluasiPelaksanaanIdRouteImport.update({
    id: '/pelaksanaan/$id',
    path: '/pelaksanaan/$id',
    getParentRoute: () => TimEvaluasiRoute,
  } as any)
const KepalaOpdDetailSopIdRoute = KepalaOpdDetailSopIdRouteImport.update({
  id: '/detail-sop/$id',
  path: '/detail-sop/$id',
  getParentRoute: () => KepalaOpdRoute,
} as any)
const KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute =
  KepalaBiroOrganisasiManajemenEvaluasiSopBuatRouteImport.update({
    id: '/buat',
    path: '/buat',
    getParentRoute: () => KepalaBiroOrganisasiManajemenEvaluasiSopRoute,
  } as any)
const TimEvaluasiPenugasanDetailIdRoute =
  TimEvaluasiPenugasanDetailIdRouteImport.update({
    id: '/detail/$id',
    path: '/detail/$id',
    getParentRoute: () => TimEvaluasiPenugasanRoute,
  } as any)
const KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute =
  KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRouteImport.update({
    id: '/detail/$id',
    path: '/detail/$id',
    getParentRoute: () => KepalaBiroOrganisasiManajemenEvaluasiSopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kepala-biro-organisasi': typeof KepalaBiroOrganisasiRouteWithChildren
  '/kepala-opd': typeof KepalaOpdRouteWithChildren
  '/tim-evaluasi': typeof TimEvaluasiRouteWithChildren
  '/tim-penyusun': typeof TimPenyusunRouteWithChildren
  '/kepala-biro-organisasi/manajemen-evaluasi-sop': typeof KepalaBiroOrganisasiManajemenEvaluasiSopRouteWithChildren
  '/kepala-biro-organisasi/manajemen-opd': typeof KepalaBiroOrganisasiManajemenOpdRoute
  '/kepala-biro-organisasi/manajemen-tim-evaluasi': typeof KepalaBiroOrganisasiManajemenTimEvaluasiRoute
  '/kepala-biro-organisasi/ttd-elektronik': typeof KepalaBiroOrganisasiTtdElektronikRoute
  '/kepala-opd/daftar-sop': typeof KepalaOpdDaftarSopRoute
  '/kepala-opd/initiate-proyek': typeof KepalaOpdInitiateProyekRoute
  '/kepala-opd/manajemen-peraturan': typeof KepalaOpdManajemenPeraturanRoute
  '/kepala-opd/manajemen-tim-penyusun': typeof KepalaOpdManajemenTimPenyusunRoute
  '/kepala-opd/pelaksana-sop': typeof KepalaOpdPelaksanaSopRoute
  '/kepala-opd/ttd-elektronik': typeof KepalaOpdTtdElektronikRoute
  '/tim-evaluasi/penugasan': typeof TimEvaluasiPenugasanRouteWithChildren
  '/tim-evaluasi/ttd-elektronik': typeof TimEvaluasiTtdElektronikRoute
  '/tim-penyusun/sop-saya': typeof TimPenyusunSopSayaRoute
  '/kepala-biro-organisasi/': typeof KepalaBiroOrganisasiIndexRoute
  '/kepala-opd/': typeof KepalaOpdIndexRoute
  '/tim-evaluasi/': typeof TimEvaluasiIndexRoute
  '/tim-penyusun/': typeof TimPenyusunIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat': typeof KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute
  '/kepala-opd/detail-sop/$id': typeof KepalaOpdDetailSopIdRoute
  '/tim-evaluasi/pelaksanaan/$id': typeof TimEvaluasiPelaksanaanIdRoute
  '/tim-penyusun/detail-sop/$id': typeof TimPenyusunDetailSopIdRoute
  '/validasi/pengesahan/$id': typeof ValidasiPengesahanIdRoute
  '/validasi/ttd/berhasil': typeof ValidasiTtdBerhasilRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/': typeof KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute
  '/tim-evaluasi/penugasan/': typeof TimEvaluasiPenugasanIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id': typeof KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute
  '/tim-evaluasi/penugasan/detail/$id': typeof TimEvaluasiPenugasanDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kepala-biro-organisasi/manajemen-opd': typeof KepalaBiroOrganisasiManajemenOpdRoute
  '/kepala-biro-organisasi/manajemen-tim-evaluasi': typeof KepalaBiroOrganisasiManajemenTimEvaluasiRoute
  '/kepala-biro-organisasi/ttd-elektronik': typeof KepalaBiroOrganisasiTtdElektronikRoute
  '/kepala-opd/daftar-sop': typeof KepalaOpdDaftarSopRoute
  '/kepala-opd/initiate-proyek': typeof KepalaOpdInitiateProyekRoute
  '/kepala-opd/manajemen-peraturan': typeof KepalaOpdManajemenPeraturanRoute
  '/kepala-opd/manajemen-tim-penyusun': typeof KepalaOpdManajemenTimPenyusunRoute
  '/kepala-opd/pelaksana-sop': typeof KepalaOpdPelaksanaSopRoute
  '/kepala-opd/ttd-elektronik': typeof KepalaOpdTtdElektronikRoute
  '/tim-evaluasi/ttd-elektronik': typeof TimEvaluasiTtdElektronikRoute
  '/tim-penyusun/sop-saya': typeof TimPenyusunSopSayaRoute
  '/kepala-biro-organisasi': typeof KepalaBiroOrganisasiIndexRoute
  '/kepala-opd': typeof KepalaOpdIndexRoute
  '/tim-evaluasi': typeof TimEvaluasiIndexRoute
  '/tim-penyusun': typeof TimPenyusunIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat': typeof KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute
  '/kepala-opd/detail-sop/$id': typeof KepalaOpdDetailSopIdRoute
  '/tim-evaluasi/pelaksanaan/$id': typeof TimEvaluasiPelaksanaanIdRoute
  '/tim-penyusun/detail-sop/$id': typeof TimPenyusunDetailSopIdRoute
  '/validasi/pengesahan/$id': typeof ValidasiPengesahanIdRoute
  '/validasi/ttd/berhasil': typeof ValidasiTtdBerhasilRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop': typeof KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute
  '/tim-evaluasi/penugasan': typeof TimEvaluasiPenugasanIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id': typeof KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute
  '/tim-evaluasi/penugasan/detail/$id': typeof TimEvaluasiPenugasanDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kepala-biro-organisasi': typeof KepalaBiroOrganisasiRouteWithChildren
  '/kepala-opd': typeof KepalaOpdRouteWithChildren
  '/tim-evaluasi': typeof TimEvaluasiRouteWithChildren
  '/tim-penyusun': typeof TimPenyusunRouteWithChildren
  '/kepala-biro-organisasi/manajemen-evaluasi-sop': typeof KepalaBiroOrganisasiManajemenEvaluasiSopRouteWithChildren
  '/kepala-biro-organisasi/manajemen-opd': typeof KepalaBiroOrganisasiManajemenOpdRoute
  '/kepala-biro-organisasi/manajemen-tim-evaluasi': typeof KepalaBiroOrganisasiManajemenTimEvaluasiRoute
  '/kepala-biro-organisasi/ttd-elektronik': typeof KepalaBiroOrganisasiTtdElektronikRoute
  '/kepala-opd/daftar-sop': typeof KepalaOpdDaftarSopRoute
  '/kepala-opd/initiate-proyek': typeof KepalaOpdInitiateProyekRoute
  '/kepala-opd/manajemen-peraturan': typeof KepalaOpdManajemenPeraturanRoute
  '/kepala-opd/manajemen-tim-penyusun': typeof KepalaOpdManajemenTimPenyusunRoute
  '/kepala-opd/pelaksana-sop': typeof KepalaOpdPelaksanaSopRoute
  '/kepala-opd/ttd-elektronik': typeof KepalaOpdTtdElektronikRoute
  '/tim-evaluasi/penugasan': typeof TimEvaluasiPenugasanRouteWithChildren
  '/tim-evaluasi/ttd-elektronik': typeof TimEvaluasiTtdElektronikRoute
  '/tim-penyusun/sop-saya': typeof TimPenyusunSopSayaRoute
  '/kepala-biro-organisasi/': typeof KepalaBiroOrganisasiIndexRoute
  '/kepala-opd/': typeof KepalaOpdIndexRoute
  '/tim-evaluasi/': typeof TimEvaluasiIndexRoute
  '/tim-penyusun/': typeof TimPenyusunIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat': typeof KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute
  '/kepala-opd/detail-sop/$id': typeof KepalaOpdDetailSopIdRoute
  '/tim-evaluasi/pelaksanaan/$id': typeof TimEvaluasiPelaksanaanIdRoute
  '/tim-penyusun/detail-sop/$id': typeof TimPenyusunDetailSopIdRoute
  '/validasi/pengesahan/$id': typeof ValidasiPengesahanIdRoute
  '/validasi/ttd/berhasil': typeof ValidasiTtdBerhasilRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/': typeof KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute
  '/tim-evaluasi/penugasan/': typeof TimEvaluasiPenugasanIndexRoute
  '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id': typeof KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute
  '/tim-evaluasi/penugasan/detail/$id': typeof TimEvaluasiPenugasanDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kepala-biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop'
    | '/kepala-biro-organisasi/manajemen-opd'
    | '/kepala-biro-organisasi/manajemen-tim-evaluasi'
    | '/kepala-biro-organisasi/ttd-elektronik'
    | '/kepala-opd/daftar-sop'
    | '/kepala-opd/initiate-proyek'
    | '/kepala-opd/manajemen-peraturan'
    | '/kepala-opd/manajemen-tim-penyusun'
    | '/kepala-opd/pelaksana-sop'
    | '/kepala-opd/ttd-elektronik'
    | '/tim-evaluasi/penugasan'
    | '/tim-evaluasi/ttd-elektronik'
    | '/tim-penyusun/sop-saya'
    | '/kepala-biro-organisasi/'
    | '/kepala-opd/'
    | '/tim-evaluasi/'
    | '/tim-penyusun/'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat'
    | '/kepala-opd/detail-sop/$id'
    | '/tim-evaluasi/pelaksanaan/$id'
    | '/tim-penyusun/detail-sop/$id'
    | '/validasi/pengesahan/$id'
    | '/validasi/ttd/berhasil'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/'
    | '/tim-evaluasi/penugasan/'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id'
    | '/tim-evaluasi/penugasan/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kepala-biro-organisasi/manajemen-opd'
    | '/kepala-biro-organisasi/manajemen-tim-evaluasi'
    | '/kepala-biro-organisasi/ttd-elektronik'
    | '/kepala-opd/daftar-sop'
    | '/kepala-opd/initiate-proyek'
    | '/kepala-opd/manajemen-peraturan'
    | '/kepala-opd/manajemen-tim-penyusun'
    | '/kepala-opd/pelaksana-sop'
    | '/kepala-opd/ttd-elektronik'
    | '/tim-evaluasi/ttd-elektronik'
    | '/tim-penyusun/sop-saya'
    | '/kepala-biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat'
    | '/kepala-opd/detail-sop/$id'
    | '/tim-evaluasi/pelaksanaan/$id'
    | '/tim-penyusun/detail-sop/$id'
    | '/validasi/pengesahan/$id'
    | '/validasi/ttd/berhasil'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop'
    | '/tim-evaluasi/penugasan'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id'
    | '/tim-evaluasi/penugasan/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/kepala-biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop'
    | '/kepala-biro-organisasi/manajemen-opd'
    | '/kepala-biro-organisasi/manajemen-tim-evaluasi'
    | '/kepala-biro-organisasi/ttd-elektronik'
    | '/kepala-opd/daftar-sop'
    | '/kepala-opd/initiate-proyek'
    | '/kepala-opd/manajemen-peraturan'
    | '/kepala-opd/manajemen-tim-penyusun'
    | '/kepala-opd/pelaksana-sop'
    | '/kepala-opd/ttd-elektronik'
    | '/tim-evaluasi/penugasan'
    | '/tim-evaluasi/ttd-elektronik'
    | '/tim-penyusun/sop-saya'
    | '/kepala-biro-organisasi/'
    | '/kepala-opd/'
    | '/tim-evaluasi/'
    | '/tim-penyusun/'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat'
    | '/kepala-opd/detail-sop/$id'
    | '/tim-evaluasi/pelaksanaan/$id'
    | '/tim-penyusun/detail-sop/$id'
    | '/validasi/pengesahan/$id'
    | '/validasi/ttd/berhasil'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/'
    | '/tim-evaluasi/penugasan/'
    | '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id'
    | '/tim-evaluasi/penugasan/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KepalaBiroOrganisasiRoute: typeof KepalaBiroOrganisasiRouteWithChildren
  KepalaOpdRoute: typeof KepalaOpdRouteWithChildren
  TimEvaluasiRoute: typeof TimEvaluasiRouteWithChildren
  TimPenyusunRoute: typeof TimPenyusunRouteWithChildren
  ValidasiPengesahanIdRoute: typeof ValidasiPengesahanIdRoute
  ValidasiTtdBerhasilRoute: typeof ValidasiTtdBerhasilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tim-penyusun': {
      id: '/tim-penyusun'
      path: '/tim-penyusun'
      fullPath: '/tim-penyusun'
      preLoaderRoute: typeof TimPenyusunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-evaluasi': {
      id: '/tim-evaluasi'
      path: '/tim-evaluasi'
      fullPath: '/tim-evaluasi'
      preLoaderRoute: typeof TimEvaluasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kepala-opd': {
      id: '/kepala-opd'
      path: '/kepala-opd'
      fullPath: '/kepala-opd'
      preLoaderRoute: typeof KepalaOpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kepala-biro-organisasi': {
      id: '/kepala-biro-organisasi'
      path: '/kepala-biro-organisasi'
      fullPath: '/kepala-biro-organisasi'
      preLoaderRoute: typeof KepalaBiroOrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-penyusun/': {
      id: '/tim-penyusun/'
      path: '/'
      fullPath: '/tim-penyusun/'
      preLoaderRoute: typeof TimPenyusunIndexRouteImport
      parentRoute: typeof TimPenyusunRoute
    }
    '/tim-evaluasi/': {
      id: '/tim-evaluasi/'
      path: '/'
      fullPath: '/tim-evaluasi/'
      preLoaderRoute: typeof TimEvaluasiIndexRouteImport
      parentRoute: typeof TimEvaluasiRoute
    }
    '/kepala-opd/': {
      id: '/kepala-opd/'
      path: '/'
      fullPath: '/kepala-opd/'
      preLoaderRoute: typeof KepalaOpdIndexRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-biro-organisasi/': {
      id: '/kepala-biro-organisasi/'
      path: '/'
      fullPath: '/kepala-biro-organisasi/'
      preLoaderRoute: typeof KepalaBiroOrganisasiIndexRouteImport
      parentRoute: typeof KepalaBiroOrganisasiRoute
    }
    '/tim-penyusun/sop-saya': {
      id: '/tim-penyusun/sop-saya'
      path: '/sop-saya'
      fullPath: '/tim-penyusun/sop-saya'
      preLoaderRoute: typeof TimPenyusunSopSayaRouteImport
      parentRoute: typeof TimPenyusunRoute
    }
    '/tim-evaluasi/ttd-elektronik': {
      id: '/tim-evaluasi/ttd-elektronik'
      path: '/ttd-elektronik'
      fullPath: '/tim-evaluasi/ttd-elektronik'
      preLoaderRoute: typeof TimEvaluasiTtdElektronikRouteImport
      parentRoute: typeof TimEvaluasiRoute
    }
    '/tim-evaluasi/penugasan': {
      id: '/tim-evaluasi/penugasan'
      path: '/penugasan'
      fullPath: '/tim-evaluasi/penugasan'
      preLoaderRoute: typeof TimEvaluasiPenugasanRouteImport
      parentRoute: typeof TimEvaluasiRoute
    }
    '/kepala-opd/ttd-elektronik': {
      id: '/kepala-opd/ttd-elektronik'
      path: '/ttd-elektronik'
      fullPath: '/kepala-opd/ttd-elektronik'
      preLoaderRoute: typeof KepalaOpdTtdElektronikRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-opd/pelaksana-sop': {
      id: '/kepala-opd/pelaksana-sop'
      path: '/pelaksana-sop'
      fullPath: '/kepala-opd/pelaksana-sop'
      preLoaderRoute: typeof KepalaOpdPelaksanaSopRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-opd/manajemen-tim-penyusun': {
      id: '/kepala-opd/manajemen-tim-penyusun'
      path: '/manajemen-tim-penyusun'
      fullPath: '/kepala-opd/manajemen-tim-penyusun'
      preLoaderRoute: typeof KepalaOpdManajemenTimPenyusunRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-opd/manajemen-peraturan': {
      id: '/kepala-opd/manajemen-peraturan'
      path: '/manajemen-peraturan'
      fullPath: '/kepala-opd/manajemen-peraturan'
      preLoaderRoute: typeof KepalaOpdManajemenPeraturanRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-opd/initiate-proyek': {
      id: '/kepala-opd/initiate-proyek'
      path: '/initiate-proyek'
      fullPath: '/kepala-opd/initiate-proyek'
      preLoaderRoute: typeof KepalaOpdInitiateProyekRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-opd/daftar-sop': {
      id: '/kepala-opd/daftar-sop'
      path: '/daftar-sop'
      fullPath: '/kepala-opd/daftar-sop'
      preLoaderRoute: typeof KepalaOpdDaftarSopRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-biro-organisasi/ttd-elektronik': {
      id: '/kepala-biro-organisasi/ttd-elektronik'
      path: '/ttd-elektronik'
      fullPath: '/kepala-biro-organisasi/ttd-elektronik'
      preLoaderRoute: typeof KepalaBiroOrganisasiTtdElektronikRouteImport
      parentRoute: typeof KepalaBiroOrganisasiRoute
    }
    '/kepala-biro-organisasi/manajemen-tim-evaluasi': {
      id: '/kepala-biro-organisasi/manajemen-tim-evaluasi'
      path: '/manajemen-tim-evaluasi'
      fullPath: '/kepala-biro-organisasi/manajemen-tim-evaluasi'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenTimEvaluasiRouteImport
      parentRoute: typeof KepalaBiroOrganisasiRoute
    }
    '/kepala-biro-organisasi/manajemen-opd': {
      id: '/kepala-biro-organisasi/manajemen-opd'
      path: '/manajemen-opd'
      fullPath: '/kepala-biro-organisasi/manajemen-opd'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenOpdRouteImport
      parentRoute: typeof KepalaBiroOrganisasiRoute
    }
    '/kepala-biro-organisasi/manajemen-evaluasi-sop': {
      id: '/kepala-biro-organisasi/manajemen-evaluasi-sop'
      path: '/manajemen-evaluasi-sop'
      fullPath: '/kepala-biro-organisasi/manajemen-evaluasi-sop'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopRouteImport
      parentRoute: typeof KepalaBiroOrganisasiRoute
    }
    '/tim-evaluasi/penugasan/': {
      id: '/tim-evaluasi/penugasan/'
      path: '/'
      fullPath: '/tim-evaluasi/penugasan/'
      preLoaderRoute: typeof TimEvaluasiPenugasanIndexRouteImport
      parentRoute: typeof TimEvaluasiPenugasanRoute
    }
    '/kepala-biro-organisasi/manajemen-evaluasi-sop/': {
      id: '/kepala-biro-organisasi/manajemen-evaluasi-sop/'
      path: '/'
      fullPath: '/kepala-biro-organisasi/manajemen-evaluasi-sop/'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopIndexRouteImport
      parentRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopRoute
    }
    '/validasi/ttd/berhasil': {
      id: '/validasi/ttd/berhasil'
      path: '/validasi/ttd/berhasil'
      fullPath: '/validasi/ttd/berhasil'
      preLoaderRoute: typeof ValidasiTtdBerhasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validasi/pengesahan/$id': {
      id: '/validasi/pengesahan/$id'
      path: '/validasi/pengesahan/$id'
      fullPath: '/validasi/pengesahan/$id'
      preLoaderRoute: typeof ValidasiPengesahanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-penyusun/detail-sop/$id': {
      id: '/tim-penyusun/detail-sop/$id'
      path: '/detail-sop/$id'
      fullPath: '/tim-penyusun/detail-sop/$id'
      preLoaderRoute: typeof TimPenyusunDetailSopIdRouteImport
      parentRoute: typeof TimPenyusunRoute
    }
    '/tim-evaluasi/pelaksanaan/$id': {
      id: '/tim-evaluasi/pelaksanaan/$id'
      path: '/pelaksanaan/$id'
      fullPath: '/tim-evaluasi/pelaksanaan/$id'
      preLoaderRoute: typeof TimEvaluasiPelaksanaanIdRouteImport
      parentRoute: typeof TimEvaluasiRoute
    }
    '/kepala-opd/detail-sop/$id': {
      id: '/kepala-opd/detail-sop/$id'
      path: '/detail-sop/$id'
      fullPath: '/kepala-opd/detail-sop/$id'
      preLoaderRoute: typeof KepalaOpdDetailSopIdRouteImport
      parentRoute: typeof KepalaOpdRoute
    }
    '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat': {
      id: '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat'
      path: '/buat'
      fullPath: '/kepala-biro-organisasi/manajemen-evaluasi-sop/buat'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopBuatRouteImport
      parentRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopRoute
    }
    '/tim-evaluasi/penugasan/detail/$id': {
      id: '/tim-evaluasi/penugasan/detail/$id'
      path: '/detail/$id'
      fullPath: '/tim-evaluasi/penugasan/detail/$id'
      preLoaderRoute: typeof TimEvaluasiPenugasanDetailIdRouteImport
      parentRoute: typeof TimEvaluasiPenugasanRoute
    }
    '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id': {
      id: '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id'
      path: '/detail/$id'
      fullPath: '/kepala-biro-organisasi/manajemen-evaluasi-sop/detail/$id'
      preLoaderRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRouteImport
      parentRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopRoute
    }
  }
}

interface KepalaBiroOrganisasiManajemenEvaluasiSopRouteChildren {
  KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute
  KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute
  KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute
}

const KepalaBiroOrganisasiManajemenEvaluasiSopRouteChildren: KepalaBiroOrganisasiManajemenEvaluasiSopRouteChildren =
  {
    KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute:
      KepalaBiroOrganisasiManajemenEvaluasiSopBuatRoute,
    KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute:
      KepalaBiroOrganisasiManajemenEvaluasiSopIndexRoute,
    KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute:
      KepalaBiroOrganisasiManajemenEvaluasiSopDetailIdRoute,
  }

const KepalaBiroOrganisasiManajemenEvaluasiSopRouteWithChildren =
  KepalaBiroOrganisasiManajemenEvaluasiSopRoute._addFileChildren(
    KepalaBiroOrganisasiManajemenEvaluasiSopRouteChildren,
  )

interface KepalaBiroOrganisasiRouteChildren {
  KepalaBiroOrganisasiManajemenEvaluasiSopRoute: typeof KepalaBiroOrganisasiManajemenEvaluasiSopRouteWithChildren
  KepalaBiroOrganisasiManajemenOpdRoute: typeof KepalaBiroOrganisasiManajemenOpdRoute
  KepalaBiroOrganisasiManajemenTimEvaluasiRoute: typeof KepalaBiroOrganisasiManajemenTimEvaluasiRoute
  KepalaBiroOrganisasiTtdElektronikRoute: typeof KepalaBiroOrganisasiTtdElektronikRoute
  KepalaBiroOrganisasiIndexRoute: typeof KepalaBiroOrganisasiIndexRoute
}

const KepalaBiroOrganisasiRouteChildren: KepalaBiroOrganisasiRouteChildren = {
  KepalaBiroOrganisasiManajemenEvaluasiSopRoute:
    KepalaBiroOrganisasiManajemenEvaluasiSopRouteWithChildren,
  KepalaBiroOrganisasiManajemenOpdRoute: KepalaBiroOrganisasiManajemenOpdRoute,
  KepalaBiroOrganisasiManajemenTimEvaluasiRoute:
    KepalaBiroOrganisasiManajemenTimEvaluasiRoute,
  KepalaBiroOrganisasiTtdElektronikRoute:
    KepalaBiroOrganisasiTtdElektronikRoute,
  KepalaBiroOrganisasiIndexRoute: KepalaBiroOrganisasiIndexRoute,
}

const KepalaBiroOrganisasiRouteWithChildren =
  KepalaBiroOrganisasiRoute._addFileChildren(KepalaBiroOrganisasiRouteChildren)

interface KepalaOpdRouteChildren {
  KepalaOpdDaftarSopRoute: typeof KepalaOpdDaftarSopRoute
  KepalaOpdInitiateProyekRoute: typeof KepalaOpdInitiateProyekRoute
  KepalaOpdManajemenPeraturanRoute: typeof KepalaOpdManajemenPeraturanRoute
  KepalaOpdManajemenTimPenyusunRoute: typeof KepalaOpdManajemenTimPenyusunRoute
  KepalaOpdPelaksanaSopRoute: typeof KepalaOpdPelaksanaSopRoute
  KepalaOpdTtdElektronikRoute: typeof KepalaOpdTtdElektronikRoute
  KepalaOpdIndexRoute: typeof KepalaOpdIndexRoute
  KepalaOpdDetailSopIdRoute: typeof KepalaOpdDetailSopIdRoute
}

const KepalaOpdRouteChildren: KepalaOpdRouteChildren = {
  KepalaOpdDaftarSopRoute: KepalaOpdDaftarSopRoute,
  KepalaOpdInitiateProyekRoute: KepalaOpdInitiateProyekRoute,
  KepalaOpdManajemenPeraturanRoute: KepalaOpdManajemenPeraturanRoute,
  KepalaOpdManajemenTimPenyusunRoute: KepalaOpdManajemenTimPenyusunRoute,
  KepalaOpdPelaksanaSopRoute: KepalaOpdPelaksanaSopRoute,
  KepalaOpdTtdElektronikRoute: KepalaOpdTtdElektronikRoute,
  KepalaOpdIndexRoute: KepalaOpdIndexRoute,
  KepalaOpdDetailSopIdRoute: KepalaOpdDetailSopIdRoute,
}

const KepalaOpdRouteWithChildren = KepalaOpdRoute._addFileChildren(
  KepalaOpdRouteChildren,
)

interface TimEvaluasiPenugasanRouteChildren {
  TimEvaluasiPenugasanIndexRoute: typeof TimEvaluasiPenugasanIndexRoute
  TimEvaluasiPenugasanDetailIdRoute: typeof TimEvaluasiPenugasanDetailIdRoute
}

const TimEvaluasiPenugasanRouteChildren: TimEvaluasiPenugasanRouteChildren = {
  TimEvaluasiPenugasanIndexRoute: TimEvaluasiPenugasanIndexRoute,
  TimEvaluasiPenugasanDetailIdRoute: TimEvaluasiPenugasanDetailIdRoute,
}

const TimEvaluasiPenugasanRouteWithChildren =
  TimEvaluasiPenugasanRoute._addFileChildren(TimEvaluasiPenugasanRouteChildren)

interface TimEvaluasiRouteChildren {
  TimEvaluasiPenugasanRoute: typeof TimEvaluasiPenugasanRouteWithChildren
  TimEvaluasiTtdElektronikRoute: typeof TimEvaluasiTtdElektronikRoute
  TimEvaluasiIndexRoute: typeof TimEvaluasiIndexRoute
  TimEvaluasiPelaksanaanIdRoute: typeof TimEvaluasiPelaksanaanIdRoute
}

const TimEvaluasiRouteChildren: TimEvaluasiRouteChildren = {
  TimEvaluasiPenugasanRoute: TimEvaluasiPenugasanRouteWithChildren,
  TimEvaluasiTtdElektronikRoute: TimEvaluasiTtdElektronikRoute,
  TimEvaluasiIndexRoute: TimEvaluasiIndexRoute,
  TimEvaluasiPelaksanaanIdRoute: TimEvaluasiPelaksanaanIdRoute,
}

const TimEvaluasiRouteWithChildren = TimEvaluasiRoute._addFileChildren(
  TimEvaluasiRouteChildren,
)

interface TimPenyusunRouteChildren {
  TimPenyusunSopSayaRoute: typeof TimPenyusunSopSayaRoute
  TimPenyusunIndexRoute: typeof TimPenyusunIndexRoute
  TimPenyusunDetailSopIdRoute: typeof TimPenyusunDetailSopIdRoute
}

const TimPenyusunRouteChildren: TimPenyusunRouteChildren = {
  TimPenyusunSopSayaRoute: TimPenyusunSopSayaRoute,
  TimPenyusunIndexRoute: TimPenyusunIndexRoute,
  TimPenyusunDetailSopIdRoute: TimPenyusunDetailSopIdRoute,
}

const TimPenyusunRouteWithChildren = TimPenyusunRoute._addFileChildren(
  TimPenyusunRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KepalaBiroOrganisasiRoute: KepalaBiroOrganisasiRouteWithChildren,
  KepalaOpdRoute: KepalaOpdRouteWithChildren,
  TimEvaluasiRoute: TimEvaluasiRouteWithChildren,
  TimPenyusunRoute: TimPenyusunRouteWithChildren,
  ValidasiPengesahanIdRoute: ValidasiPengesahanIdRoute,
  ValidasiTtdBerhasilRoute: ValidasiTtdBerhasilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
