/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimPenyusunRouteRouteImport } from './routes/tim-penyusun/route'
import { Route as TimEvaluasiRouteRouteImport } from './routes/tim-evaluasi/route'
import { Route as KepalaOpdRouteRouteImport } from './routes/kepala-opd/route'
import { Route as BiroOrganisasiRouteRouteImport } from './routes/biro-organisasi/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimPenyusunIndexRouteImport } from './routes/tim-penyusun/index'
import { Route as TimEvaluasiIndexRouteImport } from './routes/tim-evaluasi/index'
import { Route as KepalaOpdIndexRouteImport } from './routes/kepala-opd/index'
import { Route as BiroOrganisasiIndexRouteImport } from './routes/biro-organisasi/index'
import { Route as TimPenyusunSopRouteImport } from './routes/tim-penyusun/sop'
import { Route as TimPenyusunPeraturanRouteImport } from './routes/tim-penyusun/peraturan'
import { Route as TimPenyusunPelaksanaRouteImport } from './routes/tim-penyusun/pelaksana'
import { Route as KepalaOpdTteRouteImport } from './routes/kepala-opd/tte'
import { Route as KepalaOpdSopRouteImport } from './routes/kepala-opd/sop'
import { Route as BiroOrganisasiTteRouteImport } from './routes/biro-organisasi/tte'
import { Route as BiroOrganisasiTimPenyusunRouteImport } from './routes/biro-organisasi/tim-penyusun'
import { Route as BiroOrganisasiTimEvaluasiRouteImport } from './routes/biro-organisasi/tim-evaluasi'
import { Route as BiroOrganisasiOpdRouteImport } from './routes/biro-organisasi/opd'
import { Route as BiroOrganisasiGrafikEvaluasiRouteImport } from './routes/biro-organisasi/grafik-evaluasi'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TimEvaluasiPenilaianRouteRouteImport } from './routes/tim-evaluasi/penilaian/route'
import { Route as BiroOrganisasiEvaluasiRouteRouteImport } from './routes/biro-organisasi/evaluasi/route'
import { Route as TimEvaluasiPenilaianIndexRouteImport } from './routes/tim-evaluasi/penilaian/index'
import { Route as BiroOrganisasiEvaluasiIndexRouteImport } from './routes/biro-organisasi/evaluasi/index'
import { Route as TimPenyusunSopIdRouteImport } from './routes/tim-penyusun/sop.$id'
import { Route as TimPenyusunKoordinatorTteRouteImport } from './routes/tim-penyusun/koordinator/tte'
import { Route as TimPenyusunKoordinatorBeritaAcaraRouteImport } from './routes/tim-penyusun/koordinator/berita-acara'
import { Route as TimEvaluasiPenilaianOpdIdRouteImport } from './routes/tim-evaluasi/penilaian/$opdId'
import { Route as KepalaOpdSopIdRouteImport } from './routes/kepala-opd/sop.$id'
import { Route as BiroOrganisasiSopIdRouteImport } from './routes/biro-organisasi/sop.$id'
import { Route as BiroOrganisasiEvaluasiIdRouteImport } from './routes/biro-organisasi/evaluasi/$id'
import { Route as TimPenyusunKoordinatorBeritaAcaraIdRouteImport } from './routes/tim-penyusun/koordinator/berita-acara.$id'

const TimPenyusunRouteRoute = TimPenyusunRouteRouteImport.update({
  id: '/tim-penyusun',
  path: '/tim-penyusun',
  getParentRoute: () => rootRouteImport,
} as any)
const TimEvaluasiRouteRoute = TimEvaluasiRouteRouteImport.update({
  id: '/tim-evaluasi',
  path: '/tim-evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KepalaOpdRouteRoute = KepalaOpdRouteRouteImport.update({
  id: '/kepala-opd',
  path: '/kepala-opd',
  getParentRoute: () => rootRouteImport,
} as any)
const BiroOrganisasiRouteRoute = BiroOrganisasiRouteRouteImport.update({
  id: '/biro-organisasi',
  path: '/biro-organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimPenyusunIndexRoute = TimPenyusunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimPenyusunRouteRoute,
} as any)
const TimEvaluasiIndexRoute = TimEvaluasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimEvaluasiRouteRoute,
} as any)
const KepalaOpdIndexRoute = KepalaOpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KepalaOpdRouteRoute,
} as any)
const BiroOrganisasiIndexRoute = BiroOrganisasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BiroOrganisasiRouteRoute,
} as any)
const TimPenyusunSopRoute = TimPenyusunSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => TimPenyusunRouteRoute,
} as any)
const TimPenyusunPeraturanRoute = TimPenyusunPeraturanRouteImport.update({
  id: '/peraturan',
  path: '/peraturan',
  getParentRoute: () => TimPenyusunRouteRoute,
} as any)
const TimPenyusunPelaksanaRoute = TimPenyusunPelaksanaRouteImport.update({
  id: '/pelaksana',
  path: '/pelaksana',
  getParentRoute: () => TimPenyusunRouteRoute,
} as any)
const KepalaOpdTteRoute = KepalaOpdTteRouteImport.update({
  id: '/tte',
  path: '/tte',
  getParentRoute: () => KepalaOpdRouteRoute,
} as any)
const KepalaOpdSopRoute = KepalaOpdSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => KepalaOpdRouteRoute,
} as any)
const BiroOrganisasiTteRoute = BiroOrganisasiTteRouteImport.update({
  id: '/tte',
  path: '/tte',
  getParentRoute: () => BiroOrganisasiRouteRoute,
} as any)
const BiroOrganisasiTimPenyusunRoute =
  BiroOrganisasiTimPenyusunRouteImport.update({
    id: '/tim-penyusun',
    path: '/tim-penyusun',
    getParentRoute: () => BiroOrganisasiRouteRoute,
  } as any)
const BiroOrganisasiTimEvaluasiRoute =
  BiroOrganisasiTimEvaluasiRouteImport.update({
    id: '/tim-evaluasi',
    path: '/tim-evaluasi',
    getParentRoute: () => BiroOrganisasiRouteRoute,
  } as any)
const BiroOrganisasiOpdRoute = BiroOrganisasiOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => BiroOrganisasiRouteRoute,
} as any)
const BiroOrganisasiGrafikEvaluasiRoute =
  BiroOrganisasiGrafikEvaluasiRouteImport.update({
    id: '/grafik-evaluasi',
    path: '/grafik-evaluasi',
    getParentRoute: () => BiroOrganisasiRouteRoute,
  } as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TimEvaluasiPenilaianRouteRoute =
  TimEvaluasiPenilaianRouteRouteImport.update({
    id: '/penilaian',
    path: '/penilaian',
    getParentRoute: () => TimEvaluasiRouteRoute,
  } as any)
const BiroOrganisasiEvaluasiRouteRoute =
  BiroOrganisasiEvaluasiRouteRouteImport.update({
    id: '/evaluasi',
    path: '/evaluasi',
    getParentRoute: () => BiroOrganisasiRouteRoute,
  } as any)
const TimEvaluasiPenilaianIndexRoute =
  TimEvaluasiPenilaianIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TimEvaluasiPenilaianRouteRoute,
  } as any)
const BiroOrganisasiEvaluasiIndexRoute =
  BiroOrganisasiEvaluasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BiroOrganisasiEvaluasiRouteRoute,
  } as any)
const TimPenyusunSopIdRoute = TimPenyusunSopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TimPenyusunSopRoute,
} as any)
const TimPenyusunKoordinatorTteRoute =
  TimPenyusunKoordinatorTteRouteImport.update({
    id: '/koordinator/tte',
    path: '/koordinator/tte',
    getParentRoute: () => TimPenyusunRouteRoute,
  } as any)
const TimPenyusunKoordinatorBeritaAcaraRoute =
  TimPenyusunKoordinatorBeritaAcaraRouteImport.update({
    id: '/koordinator/berita-acara',
    path: '/koordinator/berita-acara',
    getParentRoute: () => TimPenyusunRouteRoute,
  } as any)
const TimEvaluasiPenilaianOpdIdRoute =
  TimEvaluasiPenilaianOpdIdRouteImport.update({
    id: '/$opdId',
    path: '/$opdId',
    getParentRoute: () => TimEvaluasiPenilaianRouteRoute,
  } as any)
const KepalaOpdSopIdRoute = KepalaOpdSopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KepalaOpdSopRoute,
} as any)
const BiroOrganisasiSopIdRoute = BiroOrganisasiSopIdRouteImport.update({
  id: '/sop/$id',
  path: '/sop/$id',
  getParentRoute: () => BiroOrganisasiRouteRoute,
} as any)
const BiroOrganisasiEvaluasiIdRoute =
  BiroOrganisasiEvaluasiIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => BiroOrganisasiEvaluasiRouteRoute,
  } as any)
const TimPenyusunKoordinatorBeritaAcaraIdRoute =
  TimPenyusunKoordinatorBeritaAcaraIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TimPenyusunKoordinatorBeritaAcaraRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biro-organisasi': typeof BiroOrganisasiRouteRouteWithChildren
  '/kepala-opd': typeof KepalaOpdRouteRouteWithChildren
  '/tim-evaluasi': typeof TimEvaluasiRouteRouteWithChildren
  '/tim-penyusun': typeof TimPenyusunRouteRouteWithChildren
  '/biro-organisasi/evaluasi': typeof BiroOrganisasiEvaluasiRouteRouteWithChildren
  '/tim-evaluasi/penilaian': typeof TimEvaluasiPenilaianRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/biro-organisasi/grafik-evaluasi': typeof BiroOrganisasiGrafikEvaluasiRoute
  '/biro-organisasi/opd': typeof BiroOrganisasiOpdRoute
  '/biro-organisasi/tim-evaluasi': typeof BiroOrganisasiTimEvaluasiRoute
  '/biro-organisasi/tim-penyusun': typeof BiroOrganisasiTimPenyusunRoute
  '/biro-organisasi/tte': typeof BiroOrganisasiTteRoute
  '/kepala-opd/sop': typeof KepalaOpdSopRouteWithChildren
  '/kepala-opd/tte': typeof KepalaOpdTteRoute
  '/tim-penyusun/pelaksana': typeof TimPenyusunPelaksanaRoute
  '/tim-penyusun/peraturan': typeof TimPenyusunPeraturanRoute
  '/tim-penyusun/sop': typeof TimPenyusunSopRouteWithChildren
  '/biro-organisasi/': typeof BiroOrganisasiIndexRoute
  '/kepala-opd/': typeof KepalaOpdIndexRoute
  '/tim-evaluasi/': typeof TimEvaluasiIndexRoute
  '/tim-penyusun/': typeof TimPenyusunIndexRoute
  '/biro-organisasi/evaluasi/$id': typeof BiroOrganisasiEvaluasiIdRoute
  '/biro-organisasi/sop/$id': typeof BiroOrganisasiSopIdRoute
  '/kepala-opd/sop/$id': typeof KepalaOpdSopIdRoute
  '/tim-evaluasi/penilaian/$opdId': typeof TimEvaluasiPenilaianOpdIdRoute
  '/tim-penyusun/koordinator/berita-acara': typeof TimPenyusunKoordinatorBeritaAcaraRouteWithChildren
  '/tim-penyusun/koordinator/tte': typeof TimPenyusunKoordinatorTteRoute
  '/tim-penyusun/sop/$id': typeof TimPenyusunSopIdRoute
  '/biro-organisasi/evaluasi/': typeof BiroOrganisasiEvaluasiIndexRoute
  '/tim-evaluasi/penilaian/': typeof TimEvaluasiPenilaianIndexRoute
  '/tim-penyusun/koordinator/berita-acara/$id': typeof TimPenyusunKoordinatorBeritaAcaraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/biro-organisasi/grafik-evaluasi': typeof BiroOrganisasiGrafikEvaluasiRoute
  '/biro-organisasi/opd': typeof BiroOrganisasiOpdRoute
  '/biro-organisasi/tim-evaluasi': typeof BiroOrganisasiTimEvaluasiRoute
  '/biro-organisasi/tim-penyusun': typeof BiroOrganisasiTimPenyusunRoute
  '/biro-organisasi/tte': typeof BiroOrganisasiTteRoute
  '/kepala-opd/sop': typeof KepalaOpdSopRouteWithChildren
  '/kepala-opd/tte': typeof KepalaOpdTteRoute
  '/tim-penyusun/pelaksana': typeof TimPenyusunPelaksanaRoute
  '/tim-penyusun/peraturan': typeof TimPenyusunPeraturanRoute
  '/tim-penyusun/sop': typeof TimPenyusunSopRouteWithChildren
  '/biro-organisasi': typeof BiroOrganisasiIndexRoute
  '/kepala-opd': typeof KepalaOpdIndexRoute
  '/tim-evaluasi': typeof TimEvaluasiIndexRoute
  '/tim-penyusun': typeof TimPenyusunIndexRoute
  '/biro-organisasi/evaluasi/$id': typeof BiroOrganisasiEvaluasiIdRoute
  '/biro-organisasi/sop/$id': typeof BiroOrganisasiSopIdRoute
  '/kepala-opd/sop/$id': typeof KepalaOpdSopIdRoute
  '/tim-evaluasi/penilaian/$opdId': typeof TimEvaluasiPenilaianOpdIdRoute
  '/tim-penyusun/koordinator/berita-acara': typeof TimPenyusunKoordinatorBeritaAcaraRouteWithChildren
  '/tim-penyusun/koordinator/tte': typeof TimPenyusunKoordinatorTteRoute
  '/tim-penyusun/sop/$id': typeof TimPenyusunSopIdRoute
  '/biro-organisasi/evaluasi': typeof BiroOrganisasiEvaluasiIndexRoute
  '/tim-evaluasi/penilaian': typeof TimEvaluasiPenilaianIndexRoute
  '/tim-penyusun/koordinator/berita-acara/$id': typeof TimPenyusunKoordinatorBeritaAcaraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biro-organisasi': typeof BiroOrganisasiRouteRouteWithChildren
  '/kepala-opd': typeof KepalaOpdRouteRouteWithChildren
  '/tim-evaluasi': typeof TimEvaluasiRouteRouteWithChildren
  '/tim-penyusun': typeof TimPenyusunRouteRouteWithChildren
  '/biro-organisasi/evaluasi': typeof BiroOrganisasiEvaluasiRouteRouteWithChildren
  '/tim-evaluasi/penilaian': typeof TimEvaluasiPenilaianRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/biro-organisasi/grafik-evaluasi': typeof BiroOrganisasiGrafikEvaluasiRoute
  '/biro-organisasi/opd': typeof BiroOrganisasiOpdRoute
  '/biro-organisasi/tim-evaluasi': typeof BiroOrganisasiTimEvaluasiRoute
  '/biro-organisasi/tim-penyusun': typeof BiroOrganisasiTimPenyusunRoute
  '/biro-organisasi/tte': typeof BiroOrganisasiTteRoute
  '/kepala-opd/sop': typeof KepalaOpdSopRouteWithChildren
  '/kepala-opd/tte': typeof KepalaOpdTteRoute
  '/tim-penyusun/pelaksana': typeof TimPenyusunPelaksanaRoute
  '/tim-penyusun/peraturan': typeof TimPenyusunPeraturanRoute
  '/tim-penyusun/sop': typeof TimPenyusunSopRouteWithChildren
  '/biro-organisasi/': typeof BiroOrganisasiIndexRoute
  '/kepala-opd/': typeof KepalaOpdIndexRoute
  '/tim-evaluasi/': typeof TimEvaluasiIndexRoute
  '/tim-penyusun/': typeof TimPenyusunIndexRoute
  '/biro-organisasi/evaluasi/$id': typeof BiroOrganisasiEvaluasiIdRoute
  '/biro-organisasi/sop/$id': typeof BiroOrganisasiSopIdRoute
  '/kepala-opd/sop/$id': typeof KepalaOpdSopIdRoute
  '/tim-evaluasi/penilaian/$opdId': typeof TimEvaluasiPenilaianOpdIdRoute
  '/tim-penyusun/koordinator/berita-acara': typeof TimPenyusunKoordinatorBeritaAcaraRouteWithChildren
  '/tim-penyusun/koordinator/tte': typeof TimPenyusunKoordinatorTteRoute
  '/tim-penyusun/sop/$id': typeof TimPenyusunSopIdRoute
  '/biro-organisasi/evaluasi/': typeof BiroOrganisasiEvaluasiIndexRoute
  '/tim-evaluasi/penilaian/': typeof TimEvaluasiPenilaianIndexRoute
  '/tim-penyusun/koordinator/berita-acara/$id': typeof TimPenyusunKoordinatorBeritaAcaraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/biro-organisasi/evaluasi'
    | '/tim-evaluasi/penilaian'
    | '/auth/login'
    | '/biro-organisasi/grafik-evaluasi'
    | '/biro-organisasi/opd'
    | '/biro-organisasi/tim-evaluasi'
    | '/biro-organisasi/tim-penyusun'
    | '/biro-organisasi/tte'
    | '/kepala-opd/sop'
    | '/kepala-opd/tte'
    | '/tim-penyusun/pelaksana'
    | '/tim-penyusun/peraturan'
    | '/tim-penyusun/sop'
    | '/biro-organisasi/'
    | '/kepala-opd/'
    | '/tim-evaluasi/'
    | '/tim-penyusun/'
    | '/biro-organisasi/evaluasi/$id'
    | '/biro-organisasi/sop/$id'
    | '/kepala-opd/sop/$id'
    | '/tim-evaluasi/penilaian/$opdId'
    | '/tim-penyusun/koordinator/berita-acara'
    | '/tim-penyusun/koordinator/tte'
    | '/tim-penyusun/sop/$id'
    | '/biro-organisasi/evaluasi/'
    | '/tim-evaluasi/penilaian/'
    | '/tim-penyusun/koordinator/berita-acara/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/biro-organisasi/grafik-evaluasi'
    | '/biro-organisasi/opd'
    | '/biro-organisasi/tim-evaluasi'
    | '/biro-organisasi/tim-penyusun'
    | '/biro-organisasi/tte'
    | '/kepala-opd/sop'
    | '/kepala-opd/tte'
    | '/tim-penyusun/pelaksana'
    | '/tim-penyusun/peraturan'
    | '/tim-penyusun/sop'
    | '/biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/biro-organisasi/evaluasi/$id'
    | '/biro-organisasi/sop/$id'
    | '/kepala-opd/sop/$id'
    | '/tim-evaluasi/penilaian/$opdId'
    | '/tim-penyusun/koordinator/berita-acara'
    | '/tim-penyusun/koordinator/tte'
    | '/tim-penyusun/sop/$id'
    | '/biro-organisasi/evaluasi'
    | '/tim-evaluasi/penilaian'
    | '/tim-penyusun/koordinator/berita-acara/$id'
  id:
    | '__root__'
    | '/'
    | '/biro-organisasi'
    | '/kepala-opd'
    | '/tim-evaluasi'
    | '/tim-penyusun'
    | '/biro-organisasi/evaluasi'
    | '/tim-evaluasi/penilaian'
    | '/auth/login'
    | '/biro-organisasi/grafik-evaluasi'
    | '/biro-organisasi/opd'
    | '/biro-organisasi/tim-evaluasi'
    | '/biro-organisasi/tim-penyusun'
    | '/biro-organisasi/tte'
    | '/kepala-opd/sop'
    | '/kepala-opd/tte'
    | '/tim-penyusun/pelaksana'
    | '/tim-penyusun/peraturan'
    | '/tim-penyusun/sop'
    | '/biro-organisasi/'
    | '/kepala-opd/'
    | '/tim-evaluasi/'
    | '/tim-penyusun/'
    | '/biro-organisasi/evaluasi/$id'
    | '/biro-organisasi/sop/$id'
    | '/kepala-opd/sop/$id'
    | '/tim-evaluasi/penilaian/$opdId'
    | '/tim-penyusun/koordinator/berita-acara'
    | '/tim-penyusun/koordinator/tte'
    | '/tim-penyusun/sop/$id'
    | '/biro-organisasi/evaluasi/'
    | '/tim-evaluasi/penilaian/'
    | '/tim-penyusun/koordinator/berita-acara/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiroOrganisasiRouteRoute: typeof BiroOrganisasiRouteRouteWithChildren
  KepalaOpdRouteRoute: typeof KepalaOpdRouteRouteWithChildren
  TimEvaluasiRouteRoute: typeof TimEvaluasiRouteRouteWithChildren
  TimPenyusunRouteRoute: typeof TimPenyusunRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tim-penyusun': {
      id: '/tim-penyusun'
      path: '/tim-penyusun'
      fullPath: '/tim-penyusun'
      preLoaderRoute: typeof TimPenyusunRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-evaluasi': {
      id: '/tim-evaluasi'
      path: '/tim-evaluasi'
      fullPath: '/tim-evaluasi'
      preLoaderRoute: typeof TimEvaluasiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kepala-opd': {
      id: '/kepala-opd'
      path: '/kepala-opd'
      fullPath: '/kepala-opd'
      preLoaderRoute: typeof KepalaOpdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biro-organisasi': {
      id: '/biro-organisasi'
      path: '/biro-organisasi'
      fullPath: '/biro-organisasi'
      preLoaderRoute: typeof BiroOrganisasiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-penyusun/': {
      id: '/tim-penyusun/'
      path: '/'
      fullPath: '/tim-penyusun/'
      preLoaderRoute: typeof TimPenyusunIndexRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/tim-evaluasi/': {
      id: '/tim-evaluasi/'
      path: '/'
      fullPath: '/tim-evaluasi/'
      preLoaderRoute: typeof TimEvaluasiIndexRouteImport
      parentRoute: typeof TimEvaluasiRouteRoute
    }
    '/kepala-opd/': {
      id: '/kepala-opd/'
      path: '/'
      fullPath: '/kepala-opd/'
      preLoaderRoute: typeof KepalaOpdIndexRouteImport
      parentRoute: typeof KepalaOpdRouteRoute
    }
    '/biro-organisasi/': {
      id: '/biro-organisasi/'
      path: '/'
      fullPath: '/biro-organisasi/'
      preLoaderRoute: typeof BiroOrganisasiIndexRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/tim-penyusun/sop': {
      id: '/tim-penyusun/sop'
      path: '/sop'
      fullPath: '/tim-penyusun/sop'
      preLoaderRoute: typeof TimPenyusunSopRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/tim-penyusun/peraturan': {
      id: '/tim-penyusun/peraturan'
      path: '/peraturan'
      fullPath: '/tim-penyusun/peraturan'
      preLoaderRoute: typeof TimPenyusunPeraturanRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/tim-penyusun/pelaksana': {
      id: '/tim-penyusun/pelaksana'
      path: '/pelaksana'
      fullPath: '/tim-penyusun/pelaksana'
      preLoaderRoute: typeof TimPenyusunPelaksanaRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/kepala-opd/tte': {
      id: '/kepala-opd/tte'
      path: '/tte'
      fullPath: '/kepala-opd/tte'
      preLoaderRoute: typeof KepalaOpdTteRouteImport
      parentRoute: typeof KepalaOpdRouteRoute
    }
    '/kepala-opd/sop': {
      id: '/kepala-opd/sop'
      path: '/sop'
      fullPath: '/kepala-opd/sop'
      preLoaderRoute: typeof KepalaOpdSopRouteImport
      parentRoute: typeof KepalaOpdRouteRoute
    }
    '/biro-organisasi/tte': {
      id: '/biro-organisasi/tte'
      path: '/tte'
      fullPath: '/biro-organisasi/tte'
      preLoaderRoute: typeof BiroOrganisasiTteRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/biro-organisasi/tim-penyusun': {
      id: '/biro-organisasi/tim-penyusun'
      path: '/tim-penyusun'
      fullPath: '/biro-organisasi/tim-penyusun'
      preLoaderRoute: typeof BiroOrganisasiTimPenyusunRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/biro-organisasi/tim-evaluasi': {
      id: '/biro-organisasi/tim-evaluasi'
      path: '/tim-evaluasi'
      fullPath: '/biro-organisasi/tim-evaluasi'
      preLoaderRoute: typeof BiroOrganisasiTimEvaluasiRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/biro-organisasi/opd': {
      id: '/biro-organisasi/opd'
      path: '/opd'
      fullPath: '/biro-organisasi/opd'
      preLoaderRoute: typeof BiroOrganisasiOpdRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/biro-organisasi/grafik-evaluasi': {
      id: '/biro-organisasi/grafik-evaluasi'
      path: '/grafik-evaluasi'
      fullPath: '/biro-organisasi/grafik-evaluasi'
      preLoaderRoute: typeof BiroOrganisasiGrafikEvaluasiRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-evaluasi/penilaian': {
      id: '/tim-evaluasi/penilaian'
      path: '/penilaian'
      fullPath: '/tim-evaluasi/penilaian'
      preLoaderRoute: typeof TimEvaluasiPenilaianRouteRouteImport
      parentRoute: typeof TimEvaluasiRouteRoute
    }
    '/biro-organisasi/evaluasi': {
      id: '/biro-organisasi/evaluasi'
      path: '/evaluasi'
      fullPath: '/biro-organisasi/evaluasi'
      preLoaderRoute: typeof BiroOrganisasiEvaluasiRouteRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/tim-evaluasi/penilaian/': {
      id: '/tim-evaluasi/penilaian/'
      path: '/'
      fullPath: '/tim-evaluasi/penilaian/'
      preLoaderRoute: typeof TimEvaluasiPenilaianIndexRouteImport
      parentRoute: typeof TimEvaluasiPenilaianRouteRoute
    }
    '/biro-organisasi/evaluasi/': {
      id: '/biro-organisasi/evaluasi/'
      path: '/'
      fullPath: '/biro-organisasi/evaluasi/'
      preLoaderRoute: typeof BiroOrganisasiEvaluasiIndexRouteImport
      parentRoute: typeof BiroOrganisasiEvaluasiRouteRoute
    }
    '/tim-penyusun/sop/$id': {
      id: '/tim-penyusun/sop/$id'
      path: '/$id'
      fullPath: '/tim-penyusun/sop/$id'
      preLoaderRoute: typeof TimPenyusunSopIdRouteImport
      parentRoute: typeof TimPenyusunSopRoute
    }
    '/tim-penyusun/koordinator/tte': {
      id: '/tim-penyusun/koordinator/tte'
      path: '/koordinator/tte'
      fullPath: '/tim-penyusun/koordinator/tte'
      preLoaderRoute: typeof TimPenyusunKoordinatorTteRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/tim-penyusun/koordinator/berita-acara': {
      id: '/tim-penyusun/koordinator/berita-acara'
      path: '/koordinator/berita-acara'
      fullPath: '/tim-penyusun/koordinator/berita-acara'
      preLoaderRoute: typeof TimPenyusunKoordinatorBeritaAcaraRouteImport
      parentRoute: typeof TimPenyusunRouteRoute
    }
    '/tim-evaluasi/penilaian/$opdId': {
      id: '/tim-evaluasi/penilaian/$opdId'
      path: '/$opdId'
      fullPath: '/tim-evaluasi/penilaian/$opdId'
      preLoaderRoute: typeof TimEvaluasiPenilaianOpdIdRouteImport
      parentRoute: typeof TimEvaluasiPenilaianRouteRoute
    }
    '/kepala-opd/sop/$id': {
      id: '/kepala-opd/sop/$id'
      path: '/$id'
      fullPath: '/kepala-opd/sop/$id'
      preLoaderRoute: typeof KepalaOpdSopIdRouteImport
      parentRoute: typeof KepalaOpdSopRoute
    }
    '/biro-organisasi/sop/$id': {
      id: '/biro-organisasi/sop/$id'
      path: '/sop/$id'
      fullPath: '/biro-organisasi/sop/$id'
      preLoaderRoute: typeof BiroOrganisasiSopIdRouteImport
      parentRoute: typeof BiroOrganisasiRouteRoute
    }
    '/biro-organisasi/evaluasi/$id': {
      id: '/biro-organisasi/evaluasi/$id'
      path: '/$id'
      fullPath: '/biro-organisasi/evaluasi/$id'
      preLoaderRoute: typeof BiroOrganisasiEvaluasiIdRouteImport
      parentRoute: typeof BiroOrganisasiEvaluasiRouteRoute
    }
    '/tim-penyusun/koordinator/berita-acara/$id': {
      id: '/tim-penyusun/koordinator/berita-acara/$id'
      path: '/$id'
      fullPath: '/tim-penyusun/koordinator/berita-acara/$id'
      preLoaderRoute: typeof TimPenyusunKoordinatorBeritaAcaraIdRouteImport
      parentRoute: typeof TimPenyusunKoordinatorBeritaAcaraRoute
    }
  }
}

interface BiroOrganisasiEvaluasiRouteRouteChildren {
  BiroOrganisasiEvaluasiIdRoute: typeof BiroOrganisasiEvaluasiIdRoute
  BiroOrganisasiEvaluasiIndexRoute: typeof BiroOrganisasiEvaluasiIndexRoute
}

const BiroOrganisasiEvaluasiRouteRouteChildren: BiroOrganisasiEvaluasiRouteRouteChildren =
  {
    BiroOrganisasiEvaluasiIdRoute: BiroOrganisasiEvaluasiIdRoute,
    BiroOrganisasiEvaluasiIndexRoute: BiroOrganisasiEvaluasiIndexRoute,
  }

const BiroOrganisasiEvaluasiRouteRouteWithChildren =
  BiroOrganisasiEvaluasiRouteRoute._addFileChildren(
    BiroOrganisasiEvaluasiRouteRouteChildren,
  )

interface BiroOrganisasiRouteRouteChildren {
  BiroOrganisasiEvaluasiRouteRoute: typeof BiroOrganisasiEvaluasiRouteRouteWithChildren
  BiroOrganisasiGrafikEvaluasiRoute: typeof BiroOrganisasiGrafikEvaluasiRoute
  BiroOrganisasiOpdRoute: typeof BiroOrganisasiOpdRoute
  BiroOrganisasiTimEvaluasiRoute: typeof BiroOrganisasiTimEvaluasiRoute
  BiroOrganisasiTimPenyusunRoute: typeof BiroOrganisasiTimPenyusunRoute
  BiroOrganisasiTteRoute: typeof BiroOrganisasiTteRoute
  BiroOrganisasiIndexRoute: typeof BiroOrganisasiIndexRoute
  BiroOrganisasiSopIdRoute: typeof BiroOrganisasiSopIdRoute
}

const BiroOrganisasiRouteRouteChildren: BiroOrganisasiRouteRouteChildren = {
  BiroOrganisasiEvaluasiRouteRoute:
    BiroOrganisasiEvaluasiRouteRouteWithChildren,
  BiroOrganisasiGrafikEvaluasiRoute: BiroOrganisasiGrafikEvaluasiRoute,
  BiroOrganisasiOpdRoute: BiroOrganisasiOpdRoute,
  BiroOrganisasiTimEvaluasiRoute: BiroOrganisasiTimEvaluasiRoute,
  BiroOrganisasiTimPenyusunRoute: BiroOrganisasiTimPenyusunRoute,
  BiroOrganisasiTteRoute: BiroOrganisasiTteRoute,
  BiroOrganisasiIndexRoute: BiroOrganisasiIndexRoute,
  BiroOrganisasiSopIdRoute: BiroOrganisasiSopIdRoute,
}

const BiroOrganisasiRouteRouteWithChildren =
  BiroOrganisasiRouteRoute._addFileChildren(BiroOrganisasiRouteRouteChildren)

interface KepalaOpdSopRouteChildren {
  KepalaOpdSopIdRoute: typeof KepalaOpdSopIdRoute
}

const KepalaOpdSopRouteChildren: KepalaOpdSopRouteChildren = {
  KepalaOpdSopIdRoute: KepalaOpdSopIdRoute,
}

const KepalaOpdSopRouteWithChildren = KepalaOpdSopRoute._addFileChildren(
  KepalaOpdSopRouteChildren,
)

interface KepalaOpdRouteRouteChildren {
  KepalaOpdSopRoute: typeof KepalaOpdSopRouteWithChildren
  KepalaOpdTteRoute: typeof KepalaOpdTteRoute
  KepalaOpdIndexRoute: typeof KepalaOpdIndexRoute
}

const KepalaOpdRouteRouteChildren: KepalaOpdRouteRouteChildren = {
  KepalaOpdSopRoute: KepalaOpdSopRouteWithChildren,
  KepalaOpdTteRoute: KepalaOpdTteRoute,
  KepalaOpdIndexRoute: KepalaOpdIndexRoute,
}

const KepalaOpdRouteRouteWithChildren = KepalaOpdRouteRoute._addFileChildren(
  KepalaOpdRouteRouteChildren,
)

interface TimEvaluasiPenilaianRouteRouteChildren {
  TimEvaluasiPenilaianOpdIdRoute: typeof TimEvaluasiPenilaianOpdIdRoute
  TimEvaluasiPenilaianIndexRoute: typeof TimEvaluasiPenilaianIndexRoute
}

const TimEvaluasiPenilaianRouteRouteChildren: TimEvaluasiPenilaianRouteRouteChildren =
  {
    TimEvaluasiPenilaianOpdIdRoute: TimEvaluasiPenilaianOpdIdRoute,
    TimEvaluasiPenilaianIndexRoute: TimEvaluasiPenilaianIndexRoute,
  }

const TimEvaluasiPenilaianRouteRouteWithChildren =
  TimEvaluasiPenilaianRouteRoute._addFileChildren(
    TimEvaluasiPenilaianRouteRouteChildren,
  )

interface TimEvaluasiRouteRouteChildren {
  TimEvaluasiPenilaianRouteRoute: typeof TimEvaluasiPenilaianRouteRouteWithChildren
  TimEvaluasiIndexRoute: typeof TimEvaluasiIndexRoute
}

const TimEvaluasiRouteRouteChildren: TimEvaluasiRouteRouteChildren = {
  TimEvaluasiPenilaianRouteRoute: TimEvaluasiPenilaianRouteRouteWithChildren,
  TimEvaluasiIndexRoute: TimEvaluasiIndexRoute,
}

const TimEvaluasiRouteRouteWithChildren =
  TimEvaluasiRouteRoute._addFileChildren(TimEvaluasiRouteRouteChildren)

interface TimPenyusunSopRouteChildren {
  TimPenyusunSopIdRoute: typeof TimPenyusunSopIdRoute
}

const TimPenyusunSopRouteChildren: TimPenyusunSopRouteChildren = {
  TimPenyusunSopIdRoute: TimPenyusunSopIdRoute,
}

const TimPenyusunSopRouteWithChildren = TimPenyusunSopRoute._addFileChildren(
  TimPenyusunSopRouteChildren,
)

interface TimPenyusunKoordinatorBeritaAcaraRouteChildren {
  TimPenyusunKoordinatorBeritaAcaraIdRoute: typeof TimPenyusunKoordinatorBeritaAcaraIdRoute
}

const TimPenyusunKoordinatorBeritaAcaraRouteChildren: TimPenyusunKoordinatorBeritaAcaraRouteChildren =
  {
    TimPenyusunKoordinatorBeritaAcaraIdRoute:
      TimPenyusunKoordinatorBeritaAcaraIdRoute,
  }

const TimPenyusunKoordinatorBeritaAcaraRouteWithChildren =
  TimPenyusunKoordinatorBeritaAcaraRoute._addFileChildren(
    TimPenyusunKoordinatorBeritaAcaraRouteChildren,
  )

interface TimPenyusunRouteRouteChildren {
  TimPenyusunPelaksanaRoute: typeof TimPenyusunPelaksanaRoute
  TimPenyusunPeraturanRoute: typeof TimPenyusunPeraturanRoute
  TimPenyusunSopRoute: typeof TimPenyusunSopRouteWithChildren
  TimPenyusunIndexRoute: typeof TimPenyusunIndexRoute
  TimPenyusunKoordinatorBeritaAcaraRoute: typeof TimPenyusunKoordinatorBeritaAcaraRouteWithChildren
  TimPenyusunKoordinatorTteRoute: typeof TimPenyusunKoordinatorTteRoute
}

const TimPenyusunRouteRouteChildren: TimPenyusunRouteRouteChildren = {
  TimPenyusunPelaksanaRoute: TimPenyusunPelaksanaRoute,
  TimPenyusunPeraturanRoute: TimPenyusunPeraturanRoute,
  TimPenyusunSopRoute: TimPenyusunSopRouteWithChildren,
  TimPenyusunIndexRoute: TimPenyusunIndexRoute,
  TimPenyusunKoordinatorBeritaAcaraRoute:
    TimPenyusunKoordinatorBeritaAcaraRouteWithChildren,
  TimPenyusunKoordinatorTteRoute: TimPenyusunKoordinatorTteRoute,
}

const TimPenyusunRouteRouteWithChildren =
  TimPenyusunRouteRoute._addFileChildren(TimPenyusunRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiroOrganisasiRouteRoute: BiroOrganisasiRouteRouteWithChildren,
  KepalaOpdRouteRoute: KepalaOpdRouteRouteWithChildren,
  TimEvaluasiRouteRoute: TimEvaluasiRouteRouteWithChildren,
  TimPenyusunRouteRoute: TimPenyusunRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
