// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

function requiredEnvironment(name: string): string {
  const value = process.env[name];
  if (value === undefined || value === '') {
    throw new Error(`${name} wajib diisi`);
  }
  return value;
}

function resolveDatabaseUrl(): string {
  if (process.env['DATABASE_URL']) {
    return process.env['DATABASE_URL'];
  }

  const port = Number(process.env['DATABASE_PORT'] ?? '3306');
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('DATABASE_PORT tidak valid');
  }

  const url = new URL('mysql://localhost');
  url.hostname = requiredEnvironment('DATABASE_HOST');
  url.port = String(port);
  url.username = requiredEnvironment('DATABASE_USER');
  url.password = requiredEnvironment('DATABASE_PASSWORD');
  url.pathname = `/${requiredEnvironment('DATABASE_NAME')}`;
  return url.toString();
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
