/**
 * Seed data untuk Daftar SOP (Kepala OPD) dan SOP Saya (Tim Penyusun).
 * Siap diganti dengan API later.
 */

import type { SOPDaftarItem, SOPSayaItem } from '@/lib/types/sop'

export type { SOPDaftarItem, SOPSayaItem }

export const SEED_SOP_DAFTAR: SOPDaftarItem[] = [
  {
    id: '1',
    nomorSOP: 'SOP/DISDIK/PLY/2026/001',
    judul: 'SOP Penerimaan Siswa Baru Tahun Ajaran 2026/2027',
    deskripsi: 'Tata cara penerimaan siswa baru dan verifikasi berkas pendaftaran.',
    waktuPenugasan: '2025-12-01',
    terakhirDiperbarui: '2026-01-15',
    timPenyusun: 'Tim Penyusun A',
    unitTerkait: 'Bidang Pendidikan Dasar',
    peraturan: 'Permendikbud No. 1/2026',
    peraturanId: 'p1',
    status: 'Berlaku',
    versi: '3.0',
    kategori: 'Pelayanan',
  },
  {
    id: '2',
    nomorSOP: 'SOP/DISDIK/PLY/2026/005',
    judul: 'SOP Pelaksanaan Ujian Akhir Sekolah',
    deskripsi: 'Prosedur pelaksanaan UAS dan pengawasan ujian.',
    waktuPenugasan: '2025-11-15',
    terakhirDiperbarui: '2026-02-01',
    timPenyusun: 'Tim Penyusun A',
    unitTerkait: 'Bidang Pendidikan Dasar',
    peraturan: 'Permendikbud No. 1/2026',
    peraturanId: 'p1',
    status: 'Terverifikasi dari Kepala Biro',
    versi: '2.1',
    kategori: 'Pelayanan',
  },
  {
    id: '3',
    nomorSOP: 'SOP/DISDIK/ADM/2026/003',
    judul: 'SOP Pengelolaan Data Kepegawaian Guru',
    deskripsi: 'Pengelolaan data guru dan update NUP/NIP.',
    waktuPenugasan: '2025-12-10',
    terakhirDiperbarui: '2026-02-05',
    timPenyusun: 'Tim Penyusun B',
    unitTerkait: 'Bidang SDM',
    peraturan: 'Permendikbud No. 5/2025',
    peraturanId: 'p2',
    status: 'Dievaluasi Tim Evaluasi',
    versi: '1.0',
    kategori: 'Administrasi',
    evaluationCaseId: 'EV-2026-001',
  },
  {
    id: '4',
    nomorSOP: 'SOP/DISDIK/PLY/2026/008',
    judul: 'SOP Pemberian Beasiswa Siswa Berprestasi',
    deskripsi: 'Syarat dan tata cara pemberian beasiswa bagi siswa berprestasi.',
    waktuPenugasan: '2025-11-20',
    terakhirDiperbarui: '2026-01-28',
    timPenyusun: 'Tim Penyusun C',
    unitTerkait: 'Bidang Pendidikan Dasar',
    peraturan: 'Perda No. 3/2025',
    peraturanId: 'p3',
    status: 'Revisi dari Tim Evaluasi',
    versi: '1.2',
    kategori: 'Pelayanan',
  },
  {
    id: '5',
    nomorSOP: 'SOP/DISDIK/ADM/2026/011',
    judul: 'SOP Pelaporan Keuangan Sekolah',
    deskripsi: 'Alur pelaporan keuangan dan pertanggungjawaban dana BOS.',
    waktuPenugasan: '2025-12-05',
    terakhirDiperbarui: '2026-02-10',
    timPenyusun: 'Tim Penyusun A',
    unitTerkait: 'Bidang Keuangan',
    peraturan: 'Permendikbud No. 8/2025',
    peraturanId: 'p4',
    status: 'Diperiksa Kepala OPD',
    versi: '1.0',
    kategori: 'Administrasi',
  },
  {
    id: '6',
    nomorSOP: 'SOP/DISDIK/PLY/2026/012',
    judul: 'SOP Pelayanan Mutasi Siswa Antar Sekolah',
    deskripsi: 'Prosedur mutasi siswa dan penerbitan surat pindah.',
    waktuPenugasan: '2026-01-08',
    terakhirDiperbarui: '2026-02-11',
    timPenyusun: 'Tim Penyusun B',
    unitTerkait: 'Bidang Pendidikan Dasar',
    peraturan: 'Permendikbud No. 1/2026',
    peraturanId: 'p1',
    status: 'Draft',
    versi: '0.5',
    kategori: 'Pelayanan',
  },
  {
    id: '7',
    nomorSOP: 'SOP/DISDIK/PLY/2026/013',
    judul: 'SOP Pengaduan Masyarakat di Bidang Pendidikan',
    deskripsi: 'Penanganan pengaduan dan respon waktu tanggap.',
    waktuPenugasan: '2025-11-01',
    terakhirDiperbarui: '2026-02-08',
    timPenyusun: 'Tim Penyusun C',
    unitTerkait: 'Bidang Pelayanan',
    peraturan: 'Perda No. 3/2025',
    peraturanId: 'p3',
    status: 'Siap Dievaluasi',
    versi: '2.0',
    kategori: 'Pelayanan',
  },
  {
    id: '8',
    nomorSOP: 'SOP/DISDIK/ADM/2026/015',
    judul: 'SOP Monitoring dan Evaluasi Program Pendidikan',
    deskripsi: 'Monitoring program dan evaluasi capaian indikator.',
    waktuPenugasan: '2025-12-15',
    terakhirDiperbarui: '2026-02-09',
    timPenyusun: 'Tim Penyusun A',
    unitTerkait: 'Bidang Program',
    peraturan: 'Permendikbud No. 5/2025',
    peraturanId: 'p2',
    status: 'Diajukan Evaluasi',
    versi: '1.1',
    kategori: 'Administrasi',
  },
]

export const SEED_PERATURAN_DAFTAR: { id: string; nama: string }[] = [
  { id: 'p1', nama: 'Permendikbud No. 1/2026' },
  { id: 'p2', nama: 'Permendikbud No. 5/2025' },
  { id: 'p3', nama: 'Perda No. 3/2025' },
  { id: 'p4', nama: 'Permendikbud No. 8/2025' },
]

export const SEED_SOP_SAYA: SOPSayaItem[] = [
  { id: '1', nomorSOP: 'PRJ-DISDIK-001/2026', judul: 'SOP Penerimaan Siswa Baru 2026', versi: '0.9', status: 'Revisi dari Tim Evaluasi', terakhirDiubah: '2026-01-28', komentarCount: 3 },
  { id: '2', nomorSOP: 'PRJ-DISDIK-002/2026', judul: 'SOP Pelayanan Perpustakaan Digital', versi: '0.5', status: 'Sedang Disusun', terakhirDiubah: '2026-01-27', komentarCount: 0 },
  { id: '3', nomorSOP: 'PRJ-DISDIK-003/2025', judul: 'SOP Ujian Akhir Semester', versi: '1.0', status: 'Diperiksa Kepala OPD', terakhirDiubah: '2026-01-20', komentarCount: 0 },
  { id: '4', nomorSOP: 'PRJ-DISDIK-004/2025', judul: 'SOP Penilaian Kinerja Guru', versi: '1.5', status: 'Revisi dari Kepala OPD', terakhirDiubah: '2025-12-15', komentarCount: 0 },
  { id: '5', nomorSOP: 'PRJ-DISDIK-005/2025', judul: 'SOP Pengadaan Buku Pelajaran', versi: '2.0', status: 'Berlaku', terakhirDiubah: '2025-11-10', komentarCount: 0 },
]
